### ISSUE TITLE
Conflict With Minechem

### ISSUE THREAD

**Issue by Amaxter** [gamerforEA/Cauldron-Reloaded#10]
http://hastebin.com/locexiceju.coffee
Using Cauldron for Forge 10.13.3.1388

**Comment by spannerman79** [comment]
This isn't a cauldron issue
This is a conflicting id
Take note of line 7
java.lang.IllegalArgumentException: Cannot set already-set enchantment

Close this issue as this is something you have to fix on your end in your configs

**Comment by Amaxter** [comment]
It works fine without Cauldron, so I believe it is a Cauldron issue.

**Comment by spannerman79** [comment]
Once again, I will outline this is not a Cauldron issue.
I placed this mod into my cauldron install - by the way I already have a 250 odd mods plus about 15 plugins running - not a single issue

Once again - its a config issue on your end

Using - http://jenkins.jakimfett.com/job/Minechem%20v5%20for%201.7.10/lastSuccessfulBuild/artifact/output/Minechem-1.7.10-5.0.5.395.jar

**Comment by Amaxter** [comment]
Yes, but Minechem offers no configuration options for enchantments. Also my instance is running around 300 mods.

**Comment by spannerman79** [comment]
Until the coder for Minechem places the enchantment ID's into config you will have to do without
https://github.com/jakimfett/Minechem/issues/700

Once again - not a cauldron issue
