### ISSUE TITLE
fmlversions.properties Not updated?

### ISSUE THREAD

**Issue by Sayshal** [gamerforEA/Cauldron-Reloaded#11]
I'm running a modpack the requires 1384 (or higher I hope...), so when adding this over top of the forge version, mods are freaking out because in the fmlversions.properties it's still reading 1370.

**Comment by gamerforEA** [comment]
Oops...

**Comment by gamerforEA** [comment]
https://github.com/gamerforEA/Cauldron-Reloaded/releases/tag/1.1388.1.0-Fix1
