### ISSUE TITLE
Cauldron 1388 Not working 

### ISSUE THREAD

**Issue by tr0nlegacy2012** [gamerforEA/Cauldron-Reloaded#15]
Upon updating my direwolf and Infinity servers using the Cauldron 1388 Fix 01 server starts but players are unable to connect. Console does not give any errors, so I am unsure where the issue is

**Comment by jburrows82** [comment]
No error, no log, and no trial and error testing information? Does this happen with vanilla forge? Are you remote hosting, local hosting? No info whatsoever.

Make sure basics are covered like port availability. Other than that, good luck.

**Comment by stevestech** [comment]
Check that your modpack does not contain Mystcraft 0.11.5.00.

**Comment by tr0nlegacy2012** [comment]
I run a multi-server network using Bungee and a vanilla hub alongside 6 modded servers. Upon trying to update to the newest Modpack versions of Direwolf, Infinity, and Resonant Rise we have run into an issue preventing players to connect to servers via the bungee. 

I am unsure of the conflict, my only thought is a possible conflict with cauldron, which was updated as forge required it. Cauldron 1388 from https://github.com/gamerforEA/Cauldron-Reloaded/releases/ 

I tested to see if players could join without being connected to the bungee, so i disconnected from bungee, and we could connect. Any insight on the issue would be great!

Bungee error: https://gist.github.com/tr0nlegacy2012/c750652cd94404d95498
Server Console: resonant rise 3 - project flux 3.2.6.0 : https://gist.github.com/tr0nlegacy2012/b9dfc1084b287b5b8499



Mystcraft is disabled.
It runs fine without Bungee, just wondering if there is going to be support for bungee - as of right now it doesn't play nice together

**Comment by jburrows82** [comment]
I assume you took this to Bungee, and what did they say?

**Comment by tr0nlegacy2012** [comment]
I have posted it, but have gotten no useful responses

**Comment by tr0nlegacy2012** [comment]
Figured it out. It was some sort of conflict with bungee and CofhCore 3.0.2

**Comment by Myrninvollo** [comment]
@tr0nlegacy2012 would be nice if you could post the fix in case other Cauldron server owners hit the same problem , thx

**Comment by vpontin** [comment]
You need to open the ticket on Cauldron-reloaded repository, OR in @Yive mirror Forum,

**Comment by tr0nlegacy2012** [comment]
https://tcpr.ca/files/fixes/BungeeCord.jar
