### ISSUE TITLE
plugin commands dont work

### ISSUE THREAD

**Issue by burntcheese** [gamerforEA/Cauldron-Reloaded#17]
Whenever i try to use a plugin command, it doesn't work.  I use uHome to set homes, and whenever i /sethome, it just says how to use it.  So I checked the config, and it's empty. wat do?

**Comment by burntcheese** [comment]
ok i fixed it, what i did is that i extracted the config file from the jar and used that.  I'm guessing cauldron reloaded doesnt generate the full config?

**Comment by spannerman79** [comment]
If the config file is in DOS format then no it won't extract it.
The only plug in I know that does this is Essentials.

I use PEX and CommandBook
