### ISSUE TITLE
Request - Update to Forge 1355

### ISSUE THREAD

**Issue by spannerman79** [gamerforEA/Cauldron-Reloaded#4]
Is there any chance that you could update Cauldron to forge 1355+ ?

Many mods have increased to want/require 1355+ now

Cheers

**Comment by gamerforEA** [comment]
Ok. 14 April I add the new version.

**Comment by spannerman79** [comment]
Thank you very much!

To date already 37 mods that I use have updated to require 1355+  CotFH was the first with their mods then it seems everyone else followed suit straight away

**Comment by spannerman79** [comment]
Thank you.  I just saw the commit 8f563faec30c8cf0c9e9b612df867b4863365669

If there are issues @gamerforEA do you want me to open a new issue or continue with this already opened issue?

**Comment by Dokman** [comment]
So you can close this issue no?

**Comment by spannerman79** [comment]
When trying to compile i got the follow issues https://gist.github.com/spannerman79/ea4afd386f9f92841bda

**Comment by gamerforEA** [comment]
https://github.com/gamerforEA/Cauldron-Reloaded/releases/tag/1.1370.1.0
