### ISSUE TITLE
ftb infinity server start problem

### ISSUE THREAD

**Issue by Syclone81** [gamerforEA/Cauldron-Reloaded#7]
when i run the new version of FTB Infinity, then the server is stoping with the follow log:

http://syclone.de/downloads/fml-server-latest.log

i hope u can help me ;) thanks!

**Comment by spannerman79** [comment]
Use Actual Java not openjdk

**Comment by jburrows82** [comment]
That's not the error --- It's because of Fastcraft

Player could so easily add detection for Cauldron and disable injection, but he refuses.

**Comment by Syclone81** [comment]
when i disable fastcraft ... the problem is the same

**Comment by jburrows82** [comment]
If you removed fast craft then the crash log won't include references of Fastcraft. So where is the new log with Fastcraft removed?

**Comment by Syclone81** [comment]
i updated the logfile ;) so u can see

**Comment by Syclone81** [comment]
ah ok is see its a port problem atm... i fix it soon i can

**Comment by Syclone81** [comment]
think the problems was the port ;( i dont see it before ... sry about this ;)

**Comment by spannerman79** [comment]
@Syclone81 please close this issue then if its resolved
