### ISSUE TITLE
[Request] Update to Forge 1377/1380

### ISSUE THREAD

**Issue by spannerman79** [gamerforEA/Cauldron-Reloaded#8]
Only when you have the time to actually do this.

To see the actual changes done you can look at http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1380-1.7.10/forge-1.7.10-10.13.3.1380-1.7.10-changelog.txt

The things that I'm interested in is particularly these;

1373 - re fluid registry.  Should help with some of the mods that haven't been updated to take into account for 1370

1376 - NBT size tracking - should help with mods like NEI etc

1377 - "junk" fluid cleanup - should prevent double listings for fluid - example itemID 1370 and 1370:1 being identical from same mod

1378 - construction phase exceptions causing server crash fix

**Comment by gamerforEA** [comment]
https://github.com/gamerforEA/Cauldron-Reloaded/releases/tag/1.1388.1.0

**Comment by 008** [comment]
tnx
